---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install package dependencies
  apt: name={{item}} state=present
  with_items:
    - git
    - python-pip
    - sshpass
    - jq
    - build-essential
    - libsqlite3-dev
    - ruby
    - ruby-dev
    - libmysqlclient-dev

- name: Install python dependencies
  pip:
    name: speedtest-cli

- name: Install ruby gem dependencies
  gem: name={{item}}
  with_items:
    - sinatra
    - sequel
    - sqlite3
    - rake
    - thin
    - rubyzip
    - mysql
