---
- name: Update hostname
  hostname:
    name: mazizone

- name: Copy /etc/hosts file
  copy:
    src: ../files/hosts
    dest: /etc/hosts

- name: Copy host.conf file
  copy:
    src: ../files/etc-host.conf
    dest: /etc/host.conf

- name: Copy /etc/network/interfaces file
  copy:
    src: ../files/network-interfaces
    dest: /etc/network/interfaces

- name: Copy wpa_supplicant.conf file
  copy:
    src: ../files/wpa_supplicant-wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf

- name: Create /etc/hostapd/ directory
  file: path=/etc/hostapd/ state=directory

- name: Copy MAZI conf directory
  copy:
    src: ../files/etc-hostapd/
    dest: /etc/hostapd/

- name: Copy dnsmasq.conf file
  copy:
    src: ../files/etc-dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: Copy mazi portal init file
  copy:
    src: ../files/etc-init/mazizone-portal.conf
    dest: /etc/init/mazizone-portal.conf

- name: Create /var/www/html/ directory
  file: path=/var/www/html/ state=directory

- name: Copy www/html/index.html file
  copy:
    src: ../files/www-html/index.html
    dest: /var/www/html/index.html

#TODO cp /etc/ networking files
#TODO resolvconf Google DNS servers
