---
- name: Create /etc/mazi directory
  file: path=/etc/mazi/ state=directory

- name: Copy MAZI conf directory
  copy:
    src: ../files/etc-mazi/
    dest: /etc/mazi/

- name: Build the MAZI portal project
  command: rake init
  args:
    chdir: /root/portal

- name: Init the MAZI portal database
  command: rake db:migrate
  args:
    chdir: /root/portal
